name: densitymatch
channels:
  - conda-forge
  - pytorch
  - open3d-admin
dependencies:
  - python
  - ipython
  - pip

  - numpy
  - scipy

  - openbabel

  - open3d

  - pytorch

  - pip:
    - molgrid